### PR TITLE
allow limitus rule mode configuration for bucket

### PR DESCRIPTION
**Pull request by benib**
This exposes the Limitus rule `mode`, so it can be set to continuous.
Config defaults to `interval` to preserve backwards compatibility.

### CODE REVIEW

**Comment by connor4312** [comment]
Hey, thanks for the PR! Please add a test case and fix the failing tests.

**Comment by benib** [comment]
@connor4312 there is now a test for continuous mode.

**Comment by benib** [comment]
@connor4312 Is there anything I could/should do here?

**Comment by connor4312** [comment]
Hey, nope, looks good. Thanks!

**Comment by connor4312** [comment]
These changes have been published in 1.2.0

**Comment by benib** [comment]
Cool. Thanks.

**Pull request merged**
